### ISSUE TITLE
getContainerData has calls to non-existent methods and returns false

### ISSUE THREAD

**Issue by joleksow** [airmoi/FileMaker#5]
Hello,

I am trying to use the getContainerData method of FileMaker.php and am running into a couple of problems:

1. On lines 524 and 553 there is a reference to $this->log, but that method doesn't exist.
2. When I disable those log methods, I'm getting a return value of false, despite the fact that I am passing a URL coming directly from the FileMaker database that appears correctly formatted. It looks like /fmi/xml/cnt/[string representing the data]. It's returning a 404. I believe I have XML web publishing enabled and that the user I'm using has that privilege. Any idea what could be causing this error?

Thanks!
John

**Comment by airmoi** [comment]
Hi John,

I've fixed it in master branch.
For the 404 error, what's the configuration of the container field ? Is it using external storage ?

Romain

**Comment by joleksow** [comment]
Thanks, Romain. 

The container field is not set to use external storage.

Attempting to hit the returned URL directly also results in a 404. This doesn't seem unusual because the URL doesn't contain any authentication information, which appears to be something that is added to the cURL request in the API when the getContainerData method is called. Would I need to make the FileMaker Server instance public in order for the URL to work?

John

**Comment by airmoi** [comment]
Is your xml cwp activated on your server ?
I remember having issues when trying to get containers while xml publishing
was not activated.
Also, grant the xml publishing extended privilege to the user and try the
request again (you should have a credential request when attempting to
access the url from your browser)


2015-10-05 15:41 GMT+02:00 joleksow <notifications@github.com>:

**Comment by joleksow** [comment]
Yes, XML publishing is activated.

The user I am connecting with has the [Full Access] access set. Under the extended privileges tab, fmxml is set to be used by the [Full Access] set. Is there anything else I should need to do to get the permissions configured correctly?

I'm still getting a 404 instead of a credential request.

**Comment by airmoi** [comment]
I've updated the test suit (test folder) could you try it and tell me if it throws any errors ?
(You'll have to upload the test db to your sevrer and update 'simpletest.php' config to point to your server IP)
